# Generated by Django 4.2.7 on 2023-11-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
