# Generated by Django 4.2.7 on 2023-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chatgroup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
